### ISSUE TITLE
yarn build succeeds even with broken App.re

### ISSUE THREAD

**Issue by zhzhang** [reasonml-community/reason-scripts#57] opened 2018-05-28 07:12 UTC
After following the setup instructions with yarn https://github.com/reasonml-community/reason-scripts
I delete a few random lines from App.re, including unbalancing brackets and jsx tags. I then run yarn build, which succeeds. When I run yarn start, the page appears blank.
I feel like a compile-time error should be thrown here.

**Comment by rrdelaney** [comment] 2018-05-28 07:27
This should be fixed in the upcoming 1.0 release 😊 can you try using reason-scripts@1.0.0-beta1 as the scripts version?

**Comment by AdamBrodzinski** [comment] 2018-05-31 16:59
This seems to be broken with beta3. I've uploaded a repro with a missing semicolon that fails to compile and is swallowed (white screen in the browser, CLI compiled).

https://github.com/AdamBrodzinski/reason-scripts-repro-57/commit/37e640304a5dac1f7c8e5b3f8b3c38b530ac47bf

**Comment by rrdelaney** [comment] 2018-05-31 17:10
@AdamBrodzinski did you get expected behavior with beta1?

**Comment by AdamBrodzinski** [comment] 2018-05-31 19:43
@rrdelaney I skipped from 0.9 to beta3 but I can also check beta1 to confirm.

**Comment by AdamBrodzinski** [comment] 2018-06-01 06:10
@rrdelaney confirmed, the repro also breaks on beta1.

**Comment by rrdelaney** [comment] 2018-06-01 06:32
Thanks for checking... just for clarity, what version of Reason CLI are you using?

**Comment by AdamBrodzinski** [comment] 2018-06-01 07:40
`reason-cli@3.2.0-darwin`. Also i'm running MacOS 10.12.4

**Comment by ruaanvds** [comment] 2018-06-03 07:45
+1 - Getting same behavior. Any workarounds?

**Comment by rrdelaney** [comment] 2018-06-05 14:52
@ruaanvds you can run “yarn bsb -make-world -w” in a separate window for now

**Closed** 2018-06-15 02:32 UTC

**Comment by rrdelaney** [comment] 2018-06-15 02:38
@zhzhang @AdamBrodzinski @ruaanvds Can you try creating a new reason-scripts app and try again?

**Comment by AdamBrodzinski** [comment] 2018-06-15 19:16
@rrdelaney  Yep, it works great now! It prints out the error to the console as expected as well as displays it into the HTML page 👍  many thanks @anmonteiro !

**Comment by anmonteiro** [comment] 2018-06-15 20:13
I'm working on a way to make this more resilient to other failures / changes in the future too.
