### ISSUE TITLE
Get SyntaxError from bs-loader

### ISSUE THREAD

**Issue by Huxpro** [reasonml-community/reason-scripts#54] opened 2018-05-23 06:51 UTC
```
./src/index.re
Module build failed: /.../my-app/node_modules/bs-loader/index.js:84
      )
      ^
SyntaxError: Unexpected token )
```

The code was created from `yarn create react-app my-app --scripts-version reason-scripts`

**Comment by rrdelaney** [comment] 2018-05-23 06:54
This seems to be a duplicate of #52. Please upgrade your version of node.

**Closed by rrdelaney** 2018-05-23 06:54 UTC

**Comment by Huxpro** [comment] 2018-05-23 06:59
@rrdelaney Gotcha, but I think asking Node >8 is too much for newcomers, especially without any error provided. Why don't we do a babel transpilation before shipping bs-loader? 
Any thoughts? @chenglou

**Comment by rrdelaney** [comment] 2018-05-23 07:06
Node 8 is the current LTS release, and anything before isn’t offered for download on the node homepage anymore.

The policy of bs-loader and tools it uses is to support the current LTS release. It doesn’t use a build step because it’s just easier to work on, contribute to, and deploy. 

I think adding a note to the README about node versions would be good though 🙂
